import Link from "next/link";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App | About",
  description: "Generated by create next app",
};

export default function About() {
  return (
    <div>
      <Link href="/">Home</Link>About
    </div>
  );
}
