import "./globals.css";
import { ReactNode } from "react";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { getServerSession } from "next-auth";

import Nav from "@/app/components/nav";
import { authOptions } from "@/config";
import Hydrate from "@/app/components/hydrate";

const font = Roboto({ subsets: ["latin"], weight: ["400", "500", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={`${font.className} mx-4 xl:mx-48`}>
        <Hydrate>
          <Nav user={session?.user} />
          {children}
        </Hydrate>
      </body>
    </html>
  );
}
